version: '3'
services:
  flask:
    container_name: flask
    build: ./flask
    image: "flask:test"
    ports:
      - "5000:5000"
    networks:
    - backend



  spring:
    container_name: spring
    build: ./spring-boot
    image: "spring:test"
    ports:
      - 8080:8080
    networks:
    - backend


  nginx:
    container_name: nginx
    build: ./nginx
    image: "nginx:test"
    ports:
      - "80:80"
    networks:
      - backend

networks:
  backend:
    driver: bridge