spring:
    http:
        encoding:
            charset: UTF-8
    h2:
        console:
            enabled: true
#     mvc:
#         view:
#             prefix: /jsp/
#             suffix: .jsp
#     output:
#         ansi:
#             enabled: always
server:
    tomcat:
        uri-encoding: UTF-8
    port: 8080